### ISSUE TITLE
Parsing error when INPUT string has commas

### ISSUE THREAD

**Issue by tryashtar** [SimeoW/BASIC-transpiler#2]
These commands both work ok
```
PRINT "A,B,C"
DRAWTEXT "A,B,C",50,50
```

But this command compiles wrongly
```
INPUT "A,B,C"
```
yielding
```
SyntaxError: "" string literal contains an unescaped line break
```

**Comment by Simewu** [comment]
Thank you very much for finding this! I really should consider rewriting this application :)

**Comment by tryashtar** [comment]
So fast! 😮 Thanks for making this! I used the miSoft basic app years ago and was so pleased to find something that could help me emulate my old silly projects.
